# Generated by Django 3.2.12 on 2024-07-03 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addfamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('relation', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.BigIntegerField()),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('vemail', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('suminsured', models.FloatField()),
                ('noofyears', models.BigIntegerField()),
                ('amount_pay_for_year', models.FloatField()),
                ('btimestamp', models.DateTimeField(auto_now=True)),
                ('bstatus', models.CharField(default='Pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('cprofile', models.FileField(upload_to='')),
                ('cstatus', models.CharField(default='On Hold', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('hospital_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.BigIntegerField()),
                ('website', models.CharField(max_length=100)),
                ('services', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('adddate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('suminsured', models.FloatField()),
                ('amount_pay_for_year', models.FloatField()),
                ('apply_for', models.CharField(max_length=100)),
                ('corona_ka_watch', models.CharField(max_length=100)),
                ('conditions', models.CharField(max_length=100)),
                ('includes', models.CharField(max_length=100)),
                ('eligibility', models.CharField(max_length=100)),
                ('roomeligibility', models.CharField(max_length=100)),
                ('prebills', models.CharField(max_length=100)),
                ('postbills', models.CharField(max_length=100)),
                ('ambulence', models.CharField(max_length=100)),
                ('excludes', models.CharField(max_length=100)),
                ('ptimestamp', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.BigIntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('cprofile', models.FileField(upload_to='')),
                ('vstatus', models.CharField(default='On Hold', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uplodfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btimestamp', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('ufile', models.FileField(upload_to='')),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_insuranceapp.buy')),
            ],
        ),
        migrations.CreateModel(
            name='Submit_Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packages', models.BigIntegerField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('hospital_name', models.CharField(max_length=100)),
                ('admit_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('doctor_name', models.CharField(max_length=100)),
                ('reasonfor_admit', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('test_reports', models.FileField(upload_to='')),
                ('discharge_summary', models.FileField(upload_to='')),
                ('final_bill', models.FileField(upload_to='')),
                ('claim_amount', models.BigIntegerField()),
                ('submit_datetime', models.DateTimeField(auto_now=True)),
                ('sstatus', models.CharField(default='Waiting', max_length=100)),
                ('reasons', models.CharField(max_length=1000)),
                ('buy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_insuranceapp.buy')),
            ],
        ),
        migrations.AddField(
            model_name='buy',
            name='packages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_insuranceapp.package'),
        ),
    ]
