# Generated by Django 3.2.12 on 2024-07-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_insuranceapp', '0002_admit_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='admit_requests',
            name='patient_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admit_requests',
            name='relationship',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
